# Generated by Django 2.2.1 on 2019-12-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommaria_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='ecommaria_app.Category'),
        ),
    ]
