# Generated by Django 2.2.1 on 2019-12-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommaria_app', '0002_product_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='categories', to='ecommaria_app.Product'),
        ),
    ]
