# Generated by Django 2.2.1 on 2019-12-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommaria_app', '0003_auto_20191213_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='ecommaria_app.Category'),
        ),
    ]
