# Generated by Django 2.2.1 on 2019-12-14 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommaria_app', '0004_auto_20191213_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
    ]
